### ISSUE TITLE
Possible to require use of front-facing camera?

### ISSUE THREAD

**Issue by tkambler** [card-io/card.io-iOS-SDK-PhoneGap#13]
Does this library support the ability to specify that card information should be collected via the front-facing camera - such as in a kiosk-type situation?

**Comment by dgoldman-ebay** [comment]
@tkambler no, we have not designed the card.io library with kiosk usage in mind.

With the front-facing camera of personal devices, we have found that it is very difficult for a user to properly position their card while simultaneously blocking their view of the screen.

**Comment by webmagnets** [comment]
Has anyone figured out how to get this to work? It is essential for my kiosk.
