### ISSUE TITLE
Is there any progress for supporting Cordova Android?

### ISSUE THREAD

**Issue by cihadhoruzoglu** [card-io/card.io-iOS-SDK-PhoneGap#14]
Hi,

I want to ask you is there any progress for supporting cordova android?

Thanks

**Comment by dgoldman-ebay** [comment]
Actually, one of your helpful fellow Cordova developers has recently registered an updated version of the plugin that now supports both iOS and Android: http://plugins.cordova.io/#/package/com.keepe.cardio
