### ISSUE TITLE
onCardIOCancel not working

### ISSUE THREAD

**Issue by engincancan** [card-io/card.io-iOS-SDK-PhoneGap#15]
onCancel function not calling. I think because of sendFailureTo function returns CDVCommandStatus_OK. Eitherway it returns to successCallback.

Thanks

**Comment by dgoldman-ebay** [comment]
@engincancan thanks for your report.

We're trying to turn over the task of maintaining this repo to the Cordova/PhoneGap community, as you folks have more directly relevant expertise than we do.

So if a change in the `sendFailureTo` function would solve this problem, then please submit that change as a Pull Request, and we'll be delighted to incorporate it into the repo.
