### ISSUE TITLE
Documentation is not updated

### ISSUE THREAD

**Issue by suhaschitade** [card-io/card.io-iOS-SDK-PhoneGap#17]
I took latest of this plugin, on each of the input field of my form. when I have given camera icon for it.
Not sure why onCardIOComplete is not getting called when I hit done. 

Please modify documentation and provide the example

**Comment by dgoldman-ebay** [comment]
@suhaschitade as explained [here](https://github.com/card-io/card.io-iOS-SDK-PhoneGap#maintenance-of-this-repository), we would like this to be a community-maintained repository.

So, ideally, you will be able to debug this problem and submit a Pull Request to the repo with a solution.

A [very recent change](https://github.com/card-io/card.io-iOS-SDK-PhoneGap/issues/15) was intended to fix a perhaps-related bug. You might want to ask the developer responsible for that change for advice.

**Comment by suhaschitade** [comment]
Thanks for letting me know dgoldman-ebay.
I will certainly research on this in my spare time and will provide you more inputs

Regards,
Suhas
