### ISSUE TITLE
Can I have earlier version please

### ISSUE THREAD

**Issue by suhaschitade** [card-io/card.io-iOS-SDK-PhoneGap#18]
Hello All,
Please let me know how to take earlier version of this cool plugin

Regards,
Suhas

**Comment by dgoldman-ebay** [comment]
@suhaschitade you can use **git** to download [any commit](https://github.com/card-io/card.io-iOS-SDK-PhoneGap/commits/master) from this git repository.

**Comment by suhaschitade** [comment]
Sorry I just realized my mistake after 3-4 hours of research I manage to fix this. No need of earlier version.

Thanks for your support
Regards,
Suhas

**Comment by dgoldman-ebay** [comment]
@suhaschitade thanks for letting us know! Glad that you've got it working now.

If you think that what you've figured out from your experience might be helpful to other developers, let us know. For example, you can submit a Pull Request to update our README.md file.
