### ISSUE TITLE
Any updates/timelines on scanExpiry support?

### ISSUE THREAD

**Issue by benjamincharity** [card-io/card.io-iOS-SDK-PhoneGap#19]
I see it inside the [view controller](https://github.com/card-io/card.io-iOS-SDK-PhoneGap/blob/207b9c36b7/src%2Fios%2FCardIO%2FCardIOPaymentViewController.h#L130) but it doesn't seem to be working. 

I also tried stubbing in support in [CardIOCordovaPlugin.m](https://github.com/card-io/card.io-iOS-SDK-PhoneGap/blob/207b9c36b7/src%2Fios%2FCardIOCordovaPlugin.m) in a fork with no luck.

Thanks!

**Comment by dgoldman-ebay** [comment]
@benjamincharity `scanExpiry` defaults to `YES`, so you shouldn't need to do anything special to enable expiry scanning.

Our implementation of expiry scanning is still in its infancy. It only works for a subset of credit cards. So you may have to try several cards to confirm that it's working correctly.

**Comment by benjamincharity** [comment]
Ahh maybe that was it. I was experimenting with Amex.  Thanks for the prompt response!
