### ISSUE TITLE
Why Hasn't Keepe's fork been merged into this one?

### ISSUE THREAD

**Issue by emgeee** [card-io/card.io-iOS-SDK-PhoneGap#22]

**Comment by dgoldman-ebay** [comment]
@emgeee this repo is the original iOS-only PhoneGap project for this SDK. [Keepe's fork](http://plugins.cordova.io/#/package/com.keepe.cardio) handles both iOS and Android.

Our intention in creating this repo was to give the PhoneGap community an initial starting point. We hoped that the community would then pick up the ball and run with it, which Keepe has done.
