### ISSUE TITLE
Help with implementation

### ISSUE THREAD

**Issue by yoursecretgirl** [card-io/card.io-iOS-SDK-PhoneGap#24]
Hi,
I'm having some trouble implementing this plugin. I done everything like the Integration instructions but I can't extract the information form the card like expiration, cvv, etc...

Can you help me?
Sorry if this is something really simple, but I'm quite new with javascript and PhoneGap and I'm still learning.

**Comment by Leeds-eBooks** [comment]
What have you got so far?

**Comment by yoursecretgirl** [comment]
Hi, Leeds-eBooks!
I have a button in the html: <button id="scanBtn">Captar Raspadinha</button>
And have the .js as the integration instructions explains. I can open the camera with the click on the button, he recognises the card between the green lines but doesn't do anything else. How can I extract the information after he recognises the card?

**Comment by yoursecretgirl** [comment]
I fixed the problem. Everything was working fine. I was testing with a debit card, that's why it wasn't working. I'm so sorry for wasting your time. Thank you so much for your attention anyway!

**Comment by Leeds-eBooks** [comment]
@yoursecretgirl No problem, glad you fixed it!
