### ISSUE TITLE
Property 'scan' does not exist on type 'typeof CardIO' - Ionic 2

### ISSUE THREAD

**Issue by gunzf** [card-io/card.io-iOS-SDK-PhoneGap#73]
Hi folks, I'm new to the Ionic framework + Angular and I'm getting this same error over and over and before submitting a new issue, I did an extensive research on similar errors but I still can't quite figure it out.
Am I missing something?

```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { CardIO } from '@ionic-native/card-io';




@IonicPage()
@Component({
  selector: 'page-payment',
  providers: [CardIO],
  templateUrl: 'payment.html'
})
export class Payment {

  constructor(public navCtrl: NavController, public navParams: NavParams, private cardIO: CardIO) {
  
  }
  ScanCard(){
    this.cardIO.canScan()
  .then(
    (res: boolean) => {
      if(res){
        let options = {
          requireExpiry: true,
          requireCCV: false,
          requirePostalCode: false
        };
        CardIO.scan(options);
      }
    }
  );
}
}
```

Thank you!

**Comment by christopherlo93** [comment]
@gunzf I think it's a typo, try:

`this.cardIO.scan(options);`

**Comment by gunzf** [comment]
@christopherlo93 Your solution fixed my IDE error, but nothing happens when run I the app on my device through Ionic View. This is so frustrating :( . But thanks for the reply!

**Comment by christopherlo93** [comment]
@gunzf Ionic View doesn't support cardIO! Compile and directly run on your phone. Check docs: https://docs.ionic.io/tools/view/

**Comment by gunzf** [comment]
@christopherlo93 Thank you mate! I wasn't aware of that support list. I've compiled and built an apk and ran on my phone and it worked! Thanks for the prompt support.
