### ISSUE TITLE
Success callback never called

### ISSUE THREAD

**Issue by globules-io** [card-io/card.io-iOS-SDK-PhoneGap#84]
### General information

* SDK/Library version: 2.1.0
* Platforms: Android
* Device OS Version and Device: Android 6

### Issue description

                       CardIO.scan({
			  "requireExpiry":true,
			  "requireCVV":false,
			  "requirePostalCode":false,
			  "hideCardIOLogo":true,
			  "keepApplicationTheme":true,
			  "allowFreelyRotatingCardGuide":false,
			  "suppressConfirmation":true
			},
			cardScanComplete,
			cardScanCancel);

upon successfull scan, cardScanCancel is called instead of cardScanComplete.
cardScanComplete is never called. Why would my scan always be canceled when it seems to do a successful scan??

**Comment by ghost** [comment]
This seems to be happening when you have **_suppressConfirmation_** set to true.

**Comment by ghost** [comment]
if (resultCode == CardIOActivity.RESULT_CARD_INFO) {
                CreditCard scanResult = null;
                if (intent.hasExtra(CardIOActivity.EXTRA_SCAN_RESULT)) {
                    scanResult = intent
                            .getParcelableExtra(CardIOActivity.EXTRA_SCAN_RESULT);
                    this.callbackContext.success(this.toJSONObject(scanResult));
                } else {
                    this.callbackContext
                            .error("card was scanned but no result");
                }
            } else if (resultCode == Activity.RESULT_CANCELED) {
                this.callbackContext.error("card scan cancelled");
            } else {
                this.callbackContext.error(resultCode);
            }

In this case, when you have **_suppressConfirmation_** set to true, control goes to the else block and your error callback is called.

**Comment by globules-io** [comment]
So I've checked and it appears to work with suppressConfirmation set to false but we really need no confirmation :(

**Comment by ghost** [comment]
Implement the plugin locally. 

And add this instead

if (resultCode == CardIOActivity.RESULT_CARD_INFO || resultCode == CardIOActivity.RESULT_CONFIRMATION_SUPPRESSED)

Should work with suppressConfirmation set to true.

**Comment by ghost** [comment]
Look at this PR

https://github.com/card-io/card.io-Cordova-Plugin/pull/80
